name: Build & Deploy

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Verify
        run: mvn --batch-mode --update-snapshots verify

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Remove -SNAPSHOT
        run: mvn versions:set --batch-mode -DremoveSnapshot
      - name: Publish package
        run: mvn --batch-mode -P github deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: dyescape-libraries
          server-username: DYESCAPE_SPACE_USERNAME
          server-password: DYESCAPE_SPACE_PASSWORD
      - name: Publish package
        run: mvn --batch-mode -P internal deploy
        env:
          DYESCAPE_SPACE_USERNAME: ${{ secrets.DYESCAPE_SPACE_USERNAME }}
          DYESCAPE_SPACE_PASSWORD: ${{ secrets.DYESCAPE_SPACE_PASSWORD }}

  publish-snapshot:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode -P github deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: dyescape-libraries
          server-username: DYESCAPE_SPACE_USERNAME
          server-password: DYESCAPE_SPACE_PASSWORD
      - name: Publish package (internal)
        run: mvn --batch-mode -P internal deploy
        env:
          DYESCAPE_SPACE_USERNAME: ${{ secrets.DYESCAPE_SPACE_USERNAME }}
          DYESCAPE_SPACE_PASSWORD: ${{ secrets.DYESCAPE_SPACE_PASSWORD }}
